services:
  server:
    image: node:12-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 4000:4000
    working_dir: /server
    volumes:
      - ./src/server:/server
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: THESEUS

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: THESEUS



volumes:
  mysql-data:


